### ISSUE TITLE
部署node.js的服务器，必须是支持https的？

### ISSUE THREAD

**Issue by liuliangjia** [dueros/bot-sdk-node.js#1]
部署node.js的服务器，必须是支持https的？

**Comment by kira3007** [comment]
出于对用户信息安全的考虑，接入DuerOS的技能，需要是https的。而且，对应的技能也应该要验证请求是否来自DuerOS，参考：https://dueros.baidu.com/didp/doc/dueros-bot-platform/dbp-deploy/authentication_markdown
